# For using the debian (ubuntu) mingw cross compiler package
# to compile a windows executable.
# There is no install target.
# *.o is removed before and after running make,
# to avoid conflicts with the normal non-cross make


CC=i586-mingw32msvc-gcc
CC=/usr/bin/x86_64-w64-mingw32-gcc

all: clean magdec.exe

magdec.exe: geomag_calc.o magdec.o Makefile.mingw32cross igrf11.h
	$(CC) -o $@ geomag_calc.o magdec.o -lm
	$(RM) *.o

clean:
	$(RM) *.o

